### 반복문 (loop)
- 파이썬의 제어문에서 반복되는 코드를 실행하는 명령어이다. 
- 너무 코드를 하드코딩하게 된다면 코드를 읽기도 피곤하고 오류가 날 확률이 높아지기 때문에 반복문을 사용한다.
+ 만약 1~5까지 숫자를 출력한다면?
- print(1) ~ print(5)까지 하면된다.
+ 만약 1~2048까지 숫자를 출력한다면?
- 이 경우 하드코딩이 어렵다.
    ```python3
    for i in range(1,2049):
        print(i)
    ```
- 와 같이 사용한다.
- 들여쓰기가 하나의 블록으로 묶여서 함께 실행되며 들여쓰기가 중요하다

In [1]:
for i in range(5):
    print('{}번째 hello!'.format(i))


0번째 hello!
1번째 hello!
2번째 hello!
3번째 hello!
4번째 hello!


### Range함수
- 범위를 표현하는 파이썬 함수이다.
- for문의 필수요소가 범위라서 range와 같이 사용되는 경우가 많다.
- 범위는 인덱싱 가능한 객체 또는 range로 표현한다.
``` python3 
range(start, stop, step)
```
- 으로 사용되고, step은 start와 stop사이에서 특정 숫자가 증가하도록 설정할 수 있다.


In [2]:
print(list(range(1,11)))
print(list(range(1,11,2))) #step에 따라서 저장되는게 다른 것을 확인할 수 있다.
print(list(range(1,11,3)))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 3, 5, 7, 9]
[1, 4, 7, 10]


- 반복문 실습 
- 제작조건
- 1. 숫자를 하나 입력받는다.
- 2. 1부터 입력받은 숫자까지의 범위에서 짝수를 출력한다.

In [3]:
def function1(num1):
    for i in range(2,num1+1,2): #1은 홀수가 아니니까 2부터로
        print(i)
a = int(input())
function1(a)


2
4
6


- 25이하의 자연수에서 2의배수 출력
- -8에서 -13범위의 정수 출력
- 30미만의 3의 배수 출력
- 0.1 0.2 0.3 0.4 0.5순서로 숫자 출력

In [4]:
def func1(max):
    print('func1')
    for i in range(2,max+1,2):
        print(i)
first = 25
func1(first)
def func2(start,end):
    print('func2')
    for i in range(end,start-1,-1): # step을 -1로하면 거꾸로도 보낼 수 있다.
        print(i)
func2(-13,-8)
def func3(max):
    print('func3')
    for i in range(1,max):
        if i %3 == 0:
            print(i)
func3(30)

def func4(num):
    print('func4')
    for i in range(1,num+1):
        print(i/10)
func4(5)

func1
2
4
6
8
10
12
14
16
18
20
22
24
func2
-8
-9
-10
-11
-12
-13
func3
3
6
9
12
15
18
21
24
27
func4
0.1
0.2
0.3
0.4
0.5


In [5]:
print(help(range)) #자기가 모르는 함수의 사용법을 알 수 있는 방법은 help를 사용하면된다

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash

### while 반복문
- for 반복문은 특정 범위 내에서 반복을 진행하는 것이고, while 반복문은 특정 조건 내에서 반복해주는 것이다.
```python
ind = 0
while ind <10:
    ind += 1
    print(ind)
```
- 과 같이 사용한다. 즉 while 뒤에 조건이 True인 경우에 계속 실행되는 것이다. 
- 주피터에서 무한반복이 실행되면 컨트롤이 어렵다. 주피터에서 무한반복일 때 처리하는 방법은 정지버튼을 눌러서 종료하는 방법이 있다.

In [6]:
ind = 0
while ind <10:
    print('{}번째 while문 실행'.format(ind))
    ind += 1

0번째 while문 실행
1번째 while문 실행
2번째 while문 실행
3번째 while문 실행
4번째 while문 실행
5번째 while문 실행
6번째 while문 실행
7번째 while문 실행
8번째 while문 실행
9번째 while문 실행


- 숫자 하나 입력받는다.
- 1부터 입력받은 숫자까지의 범위에서 짝수를 출력한다.

In [7]:
num = int(input())
i = 2
while i <= num:
    print(i)
    i += 2


2
4
6


- continue : 다음 루프로 이동 (현재 루프 종료)
- break : 반복문 종료
- pass : 아무 영향 없음 그냥 말 그대로 pass

In [8]:
for i in range(1,11):
    print(i)
    continue
    print('실행 안됨')
for i in range(1,11):
    print(i)
    break
    print('반복문 즉시 종료')
for i in range(1,11):
    print(i)
    pass
    print('실행 안됨') #아무것도 안하고 그냥 다 출력해줌

1
2
3
4
5
6
7
8
9
10
1
1
실행 안됨
2
실행 안됨
3
실행 안됨
4
실행 안됨
5
실행 안됨
6
실행 안됨
7
실행 안됨
8
실행 안됨
9
실행 안됨
10
실행 안됨


- pass를 사용하는 이유 : 코드블록을 채우기 위해서, 아무것도 안한다는 것을 명시적으로 보여주기 위해서
- 이중 반복문은 사용하는 경우가 종종있지만, 파이썬에서 반복문은 느린 코드에 속하기 때문에 최대한 지양하는 편이 좋다.

- 다중 루프 실습
- 아래 데이터를 이용해 예시대로 출력해보자
```python
list1 = [[1,2,3],[4,5,6],[7,8,9]]
```
1. 예시 1 
- 1 2 3
- 4 5 6
- 7 8 9
2. 예시 2
- 1 2 3 4 5 6 7 8 9 


In [9]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]

def sol1(list1):
    print('예시 1')
    for i in list1:
        print(' '.join(list(map(str,i))))
    
    

sol1(list1)
def sol1_1(list1):
    print('예시 1-1')
    for i in list1: 
        for j in i:
            print(j,end=' ')
        print() #중간에 그냥 print를 해줘서 한줄 넘기기를 통해서 더 간단하게 처리할 수 있다.
sol1_1(list1)
def sol2(list1):
    print('예시 2')
    for i in list1:
        for j in i:
            print(j,end=' ') #end default값은 \n임(다음 줄) 이것을 ' '으로 변경해주는 것임
    
sol2(list1)
def sol3(list1):
    print('\n예시 3 대각선으로 쭉 출력하기')
    count = 0
    for i in list1:
        for j in i:
            print(' '*count,j)
            count += 1

sol3(list1)

예시 1
1 2 3
4 5 6
7 8 9
예시 1-1
1 2 3 
4 5 6 
7 8 9 
예시 2
1 2 3 4 5 6 7 8 9 
예시 3 대각선으로 쭉 출력하기
 1
  2
   3
    4
     5
      6
       7
        8
         9


- join 함수는 str에만 사용되기 때문에 숫자로 입력받는 것을 list(map(str,리스트)) 로 매핑을 str로 해줘야지 제대로 진행된다.
- print에 end를 공백으로 설정해주면 프린트가 될 때 엔터가 아닌 띄어쓰기로 설정된다.

- 아래 조건을 고려해 프로그램을 만들자.
1. 숫자 하나를 입력받는다
2. 1부터 입력받은 숫자까지의 범위에서 짝수만 선택한다.
3. (b)의 숫자 각각 팩토리얼 연산 결과를 구해 출력한다.

In [15]:
num = int(input()) 
#num = 6
def sol4(num):
    result_list = []
    for i in range(1,num+1):
        
        if i %2 == 0:
            sum = 1
            for j in range(1,i+1):
                sum *= j
            result_list.append(sum)
        else:
            pass
    return result_list

result_list = sol4(num)
print(' '.join(list(map(str,result_list))))

def sol5(num):#이와 같이 더 간단하게 작성할 수 있다.
    
    for i in range(2,num+1,2):
        sum = 1
        for j in range(1,i+1):
            sum*=j
        print('{}의 팩토리얼 값은 {}입니다.'.format(i,sum))
sol5(6)


2 24 720
2의 팩토리얼 값은 2입니다.
4의 팩토리얼 값은 24입니다.
6의 팩토리얼 값은 720입니다.


- 0을 어떠한 숫자로 나누게 되면 파이썬에서는 0이 나오게 되므로 항상 범위에 유의하도록 하자
### 포매팅(formatting) 은 문자열을 입력할 때 사용되는 편리한 기법
```python
x = 123
y = 456
z = 789
print('x는 123, y는 456, z는 789이다')
```
- 위와 같은 상황에서 값이 변할때 자동으로 적용시키기 위한 방법이다.

In [22]:
x = 123
y = 45.6
z = [7,8,9]
print('x는 %d이고, y는 %0.1f, z는 %s이다.'%(x,y,z)) #f는 float, s는 sentence이다.
#혹은 다음과 같이 사용할 수 있다.
print('x는 {}, y는 {}, z는 {}이다.'.format(x,y,z)) #이 방법은 자료형을 안따져도 된다.
# 혹은 다음과 같이 사용할 수 있다.
print(f'x는 {x}, y는 {y}, z는 {z}이다.') #문자열 앞에 f를 붙이고 중괄호로 묶어서 바로 처리할 수 있다.

x는 123이고, y는 45.6, z는 [7, 8, 9]이다.
x는 123, y는 45.6, z는 [7, 8, 9]이다.
x는 123, y는 45.6, z는 [7, 8, 9]이다.


In [48]:
#인덱싱과 슬라이싱
lista = [i for i in range(10)]
print(lista)
print(lista[:3])
print(lista[2:])
print(lista[::2]) #처음부터 끝까지 step은 2씩 건너뛰면서
print(lista[::-1]) #처음부터 끝까진데 뒤에서부터 쭈욱
print(lista[::-2]) #뒤에서부터 2개씩 건너뛰면서
print(lista[-2::-2])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2]
[2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[9, 7, 5, 3, 1]
[8, 6, 4, 2, 0]


### 매트릭스(Matrix)는 행렬이나 표를 나타내는 데이터 형식이다.
- 행렬데이터는 파이썬에서 기본적으로는 지원하지 않는다. array가 있지만 노력대비 가성비가 안나오니 numpy를 사용한다.
- numpy는 파이썬에서 배열연산, ndarray 자료형을 제공해준다.
- 구성요소의 자료형이 통일되어있다. 다른 언어에서 배열을 나타냄
- 브로드캐스팅이라는 연산을 지원한다.(일괄 연산)
```python
lista = [1,2,3,4,5]#의 원소를 4씩 곱하고 싶다.
``` 
- 위와 같은 경우에 numpy array를 사용하면 일괄적으로 한번에 구할 수 있다.
- 사용하는 이유 
1. 넘파이는 배열연산을 할 때 파이썬에서 가장 많이 사용된다.
2. 수학적인 행렬에 완벽하게 대응한다. (기본 함수로는 부족하다)
3. 브로드캐스팅 때문에 속도가 빠르기 때문에 사용한다. (또한 외부 구조가 c언어로 이루어져있어서 빠르다.)

In [51]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1[2]) #index 가능
print(arr1[:3]) #slice 가능
print(arr1+1) #브로드캐스팅 가능
print(arr1*4) #각각의 값이 4배가 되는 것 확인 가능
print(arr1.shape)
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3 = np.array([[4],[5],[6]])
print(arr2.shape)
print(arr3.shape)
print(arr2.dot(arr3),arr2.dot(arr3).shape) #행렬곱 가능
arr4 = np.array([[1],[2],[3],[4],[5]])
print(arr1.dot(arr4))

[1 2 3 4 5]
<class 'numpy.ndarray'>
3
[1 2 3]
[2 3 4 5 6]
[ 4  8 12 16 20]
(5,)
(3, 3)
(3, 1)
[[ 32]
 [ 77]
 [122]] (3, 1)
[55]


- 파이썬에서 파일을 저장하거나 불러올때가 있는데 txt의 경우에는 파이썬 문자열 처리를 통하면 되지만, 데이터 타입이 행렬이나 다른 형식이라면 저장하기가 까다롭다. 
- 그래서 numpy와 같은 특수한 형태의 데이터를 저장하는 경우엔 np.save / np.savez / np.load 와 같이 저장하고 불러올 수 있다.
- npy는 numpy array 확장자이다.
- npz는 행렬의 집합과 같은 느낌이다. 
- 아래 예제들은 절대경로(실제로 저장되어있는 경로)와 상대경로(현재 폴더 위치 기준으로 상대적인 파일 저장 경로)로 저장하는 것을 보여준다.

In [74]:
np.save('/Users/BIG3-09/Desktop/codezip/savetest.npy',arr2)
load_test_arr = np.load('/Users/BIG3-09/Desktop/codezip/savetest.npy')
print(arr2)
print(load_test_arr)

np.savez('/Users/BIG3-09/Desktop/codezip/savetest2.npz',A=arr2,B=load_test_arr) #A 와 B를 압축해서 저장
load_test_arr2 = np.load('/Users/BIG3-09/Desktop/codezip/savetest2.npz')['A'] #A에 해당하는거 가져옴
load_test_arr3 = np.load('/Users/BIG3-09/Desktop/codezip/savetest2.npz')['B'] #B에 해당하는거 가져옴
print(load_test_arr2)
print(load_test_arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [75]:
np.save('../savetest.npy',arr2)
load_test_arr = np.load('../savetest.npy')
print(arr2)
print(load_test_arr)

np.savez('../savetest2.npz',A=arr2,B=load_test_arr) #A 와 B를 압축해서 저장
load_test_arr2 = np.load('../savetest2.npz')['A'] #A에 해당하는거 가져옴
load_test_arr3 = np.load('../savetest2.npz')['B'] #B에 해당하는거 가져옴
print(load_test_arr2)
print(load_test_arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


자소서에 운동관련 이야기를 적으면 
1. 건강관리하는 이미지
2. 일할때 하는 이미지를 줄 수 있다. 

### 판다스 (Pandas)
- 표 형식 데이터 패키지
- DataFrame, Series(dictionary같이 key value) 객체 지원
- column - row 구조의 표 지원 (column name : header / row name : index)
- 엑셀 파일 호환
- 브로드캐스팅 지원 (numpy보다 느림, 자료형이 통일되어있지 않다)

In [89]:
import pandas as pd

df = pd.DataFrame([[1,2,3,4,5],[4,5,6,7,8],[5,6,7,8,9]])
print(df)

print('column index \n{}'.format(df[1]))
print('column index \n{}'.format(df[1][1]))

print('row index \n{}'.format(df.loc[1]))
print('row index \n{}'.format(df.loc[1][1]))

   0  1  2  3  4
0  1  2  3  4  5
1  4  5  6  7  8
2  5  6  7  8  9
column index 
0    2
1    5
2    6
Name: 1, dtype: int64
column index 
5
row index 
0    4
1    5
2    6
3    7
4    8
Name: 1, dtype: int64
row index 
5


In [104]:
print('row slice \n{}'.format(df[:3]))
print('row slice \n{}'.format(df.loc[:3]))
print('복합 슬라이싱 \n{}'.format(df.loc[:3,:1])) # loc으로 해서 row 몇번째 ',' column 몇번째
#loc를 사용하게 되면 순서가 row, column으로 설정이 되기 때문에 사용해주는 것이 매우매우매우 좋다. 또한 loc함수를 사용하면 범위가 아닌 이름 기반으로 적용된다.


row slice 
   0  1  2  3  4
0  1  2  3  4  5
1  4  5  6  7  8
2  5  6  7  8  9
row slice 
   0  1  2  3  4
0  1  2  3  4  5
1  4  5  6  7  8
2  5  6  7  8  9
column slice 
   0  1
0  1  2
1  4  5
2  5  6


In [106]:
print('iloc test \n{}'.format(df.iloc[:1,:2]))
print('iloc test \n{}'.format(df.iloc[:2,:4]))

iloc test 
   0  1
0  1  2
iloc test 
   0  1  2  3
0  1  2  3  4
1  4  5  6  7


- pandas에서 loc를 쓰면 이름 기반 index, slice이다. 
- iloc를 사용하면 숫자 기반 index, slice이다 (코딩할 때 자주 사용되는 것)

In [110]:
print(df[0]*4) #브로드캐스팅 지원
print(df[1] + 1)

0     4
1    16
2    20
Name: 0, dtype: int64
0    3
1    6
2    7
Name: 1, dtype: int64


In [135]:
df.to_csv('../df.csv')
df.to_excel('../df.xlsx')
print('저장 전 \n',df)
load_df = pd.read_csv('../df.csv')
load_df2 = pd.read_excel('../df.xlsx')
print(load_df)
print(load_df2) #저장하고 불러오니까 Unamed가 생겼다.
load_df = pd.read_csv('../df.csv',index_col=0) #이렇게 처리하면 Unnamed가 사라진다. header를 설정해줄 수 있고, 저장할 때 index = False를 하면 index를 빼고 저장할 수 있다.
print(load_df)

저장 전 
    0  1  2  3  4
0  1  2  3  4  5
1  4  5  6  7  8
2  5  6  7  8  9
   Unnamed: 0  0  1  2  3  4
0           0  1  2  3  4  5
1           1  4  5  6  7  8
2           2  5  6  7  8  9
   Unnamed: 0  0  1  2  3  4
0           0  1  2  3  4  5
1           1  4  5  6  7  8
2           2  5  6  7  8  9
   0  1  2  3  4
0  1  2  3  4  5
1  4  5  6  7  8
2  5  6  7  8  9


In [170]:
test_df = pd.DataFrame([[1,2,3,4,5],[4,5,6,7,8],[5,6,7,8,9],[10,11,12,13,14]]) # 4*5 생성
len_col = test_df.shape[1]
print(test_df)
for i in range(len_col):
    test_df[i] = (test_df[i]+1)*2
    test_df = test_df.rename({i:f'calc_{i}'},axis=1)
import time
test_df.to_csv(f'../{time.localtime().tm_year}_{time.localtime().tm_mon}_{time.localtime().tm_mday}_testdf.csv',encoding='cp949')
print(test_df)

    0   1   2   3   4
0   1   2   3   4   5
1   4   5   6   7   8
2   5   6   7   8   9
3  10  11  12  13  14
   calc_0  calc_1  calc_2  calc_3  calc_4
0       4       6       8      10      12
1      10      12      14      16      18
2      12      14      16      18      20
3      22      24      26      28      30


- 한국어를 지원하는 파일인지 확인할 수 있는 방법
```python
pd.read_csv('파일 이름',encoding='cp949') # or utf-8
```
- 이를 통해서 한국어를 지원하는 파일인지 확인할 수 있다.

### 함수 (function)
- 일정한 동작을 수행하는 코드의 집합
- 기능을 손쉽게 여러번 사용가능 , 패키지 제작 가능
```python
def 함수이름(파라미터):
    함수에서 실행될 코드
    return 리턴값
```
- return은 정보 조회, 편집의 권한이 컴퓨터한테 있다.
- print는 정보 조회, 편집의 권한이 사람에게 있다.
- 이 두가지의 차이로 인해서 return에 print를 하면 컴퓨터는 접근할 수 없다.(사람은 볼 수 있다)

In [183]:
def testfunction(input):
    return input + 1
    return input + 2 #이와 같이 return은 값 반환을 하고 함수를 즉시 종료해준다.

returninput = testfunction(3)
print(returninput)

def testfunc1():
    return 'func1 : hello?'

def testfunc2():
    return print('func2 : hello?') #return값에 print가 있으면 선언만 사용해서 프린트를 사용할 수 있다.

a = testfunc1()#선언 시 출력 안됨 - 프린트 안해서 사람에게 보이지 않음
b = testfunc2()#선언 시 바로 출력
print(a)
print(b) #print로 출력하고 output이 None값으로 되어있음


4
func2 : hello?
func1 : hello?
None


In [182]:
def func1(x,y):
    if x/y > x-y:
        return 'Type |'
    else:
        return 'Type ||'
    
result = func1(7,5)
result2 = func1(6,5)

print(result)
print(result2)

Type ||
Type |


In [185]:
def func3(x):
    if x % 2 == 0:
        return x+10
    return x+100 #return의 특성을 사용해서 if-else를 대체할 수 있다.
a = func3(10)
print(a)
b = func3(11)
print(b)

def func4(x):
    return x+10, x+100 #이런식으로 다양하게 리턴해줄수있다.

a,b = func4(10)
print(a,b)

20
111
20 110
